/*
** get_syscall_name.c for get_syscall_name in /home/zeng_d
**
** Made by David Zeng
** Login   <zeng_d@epitech.net>
**
** Started on  Wed Apr 12 01:20:35 2017 David Zeng
** Last update Wed Apr 12 01:20:35 2017 David Zeng
*/

#include "strace.h"

static char	*g_syscalls[] = {
  "read",
  "write",
  "open",
  "close",
  "stat",
  "fstat",
  "lstat",
  "poll",
  "lseek",
  "mmap",
  "mprotect",
  "munmap",
  "brk",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "ioctl",
  "pread64",
  "pwrite64",
  "readv",
  "writev",
  "access",
  "pipe",
  "select",
  "sched_yield",
  "mremap",
  "msync",
  "mincore",
  "madvise",
  "shmget",
  "shmat",
  "shmctl",
  "dup",
  "dup2",
  "pause",
  "nanosleep",
  "getitimer",
  "alarm",
  "setitimer",
  "getpid",
  "sendfile",
  "socket",
  "connect",
  "accept",
  "sendto",
  "recvfrom",
  "sendmsg",
  "recvmsg",
  "shutdown",
  "bind",
  "listen",
  "getsockname",
  "getpeername",
  "socketpair",
  "setsockopt",
  "getsockopt",
  "clone",
  "fork",
  "vfork",
  "execve",
  "exit",
  "wait4",
  "kill",
  "uname",
  "semget",
  "semop",
  "semctl",
  "shmdt",
  "msgget",
  "msgsnd",
  "msgrcv",
  "msgctl",
  "fcntl",
  "flock",
  "fsync",
  "fdatasync",
  "truncate",
  "ftruncate",
  "getdents",
  "getcwd",
  "chdir",
  "fchdir",
  "rename",
  "mkdir",
  "rmdir",
  "creat",
  "link",
  "unlink",
  "symlink",
  "readlink",
  "chmod",
  "fchmod",
  "chown",
  "fchown",
  "lchown",
  "umask",
  "gettimeofday",
  "getrlimit",
  "getrusage",
  "sysinfo",
  "times",
  "ptrace",
  "getuid",
  "syslog",
  "getgid",
  "setuid",
  "setgid",
  "geteuid",
  "getegid",
  "setpgid",
  "getppid",
  "getpgrp",
  "setsid",
  "setreuid",
  "setregid",
  "getgroups",
  "setgroups",
  "setresuid",
  "getresuid",
  "setresgid",
  "getresgid",
  "getpgid",
  "setfsuid",
  "setfsgid",
  "getsid",
  "capget",
  "capset",
  "rt_sigpending",
  "rt_sigtimedwait",
  "rt_sigqueueinfo",
  "rt_sigsuspend",
  "sigaltstack",
  "utime",
  "mknod",
  "uselib",
  "personality",
  "ustat",
  "statfs",
  "fstatfs",
  "sysfs",
  "getpriority",
  "setpriority",
  "sched_setparam",
  "sched_getparam",
  "sched_setscheduler",
  "sched_getscheduler",
  "sched_get_priority_max",
  "sched_get_priority_min",
  "sched_rr_get_interval",
  "mlock",
  "munlock",
  "mlockall",
  "munlockall",
  "vhangup",
  "modify_ldt",
  "pivot_root",
  "_sysctl",
  "prctl",
  "arch_prctl",
  "adjtimex",
  "setrlimit",
  "chroot",
  "sync",
  "acct",
  "settimeofday",
  "mount",
  "umount2",
  "swapon",
  "swapoff",
  "reboot",
  "sethostname",
  "setdomainname",
  "iopl",
  "ioperm",
  "create_module",
  "init_module",
  "delete_module",
  "get_kernel_syms",
  "query_module",
  "quotactl",
  "nfsservctl",
  "getpmsg",
  "putpmsg",
  "afs_syscall",
  "tuxcall",
  "security",
  "gettid",
  "readahead",
  "setxattr",
  "lsetxattr",
  "fsetxattr",
  "getxattr",
  "lgetxattr",
  "fgetxattr",
  "listxattr",
  "llistxattr",
  "flistxattr",
  "removexattr",
  "lremovexattr",
  "fremovexattr",
  "tkill",
  "time",
  "futex",
  "sched_setaffinity",
  "sched_getaffinity",
  "set_thread_area",
  "io_setup",
  "io_destroy",
  "io_getevents",
  "io_submit",
  "io_cancel",
  "get_thread_area",
  "lookup_dcookie",
  "epoll_create",
  "epoll_ctl_old",
  "epoll_wait_old",
  "remap_file_pages",
  "getdents64",
  "set_tid_address",
  "restart_syscall",
  "semtimedop",
  "fadvise64",
  "timer_create",
  "timer_settime",
  "timer_gettime",
  "timer_getoverrun",
  "timer_delete",
  "clock_settime",
  "clock_gettime",
  "clock_getres",
  "clock_nanosleep",
  "exit_group",
  "epoll_wait",
  "epoll_ctl",
  "tgkill",
  "utimes",
  "vserver",
  "mbind",
  "set_mempolicy",
  "get_mempolicy",
  "mq_open",
  "mq_unlink",
  "mq_timedsend",
  "mq_timedreceive",
  "mq_notify",
  "mq_getsetattr",
  "kexec_load",
  "waitid",
  "add_key",
  "request_key",
  "keyctl",
  "ioprio_set",
  "ioprio_get",
  "inotify_init",
  "inotify_add_watch",
  "inotify_rm_watch",
  "migrate_pages",
  "openat",
  "mkdirat",
  "mknodat",
  "fchownat",
  "futimesat",
  "newfstatat",
  "unlinkat",
  "renameat",
  "linkat",
  "symlinkat",
  "readlinkat",
  "fchmodat",
  "faccessat",
  "pselect6",
  "ppoll",
  "unshare",
  "set_robust_list",
  "get_robust_list",
  "splice",
  "tee",
  "sync_file_range",
  "vmsplice",
  "move_pages",
  "utimensat",
  "epoll_pwait",
  "signalfd",
  "timerfd_create",
  "eventfd",
  "fallocate",
  "timerfd_settime",
  "timerfd_gettime",
  "accept4",
  "signalfd4",
  "eventfd2",
  "epoll_create1",
  "dup3",
  "pipe2",
  "inotify_init1",
  "preadv",
  "pwritev",
  "rt_tgsigqueueinfo",
  "perf_event_open",
  "recvmmsg",
  "fanotify_init",
  "fanotify_mark",
  "prlimit64",
  "name_to_handle_at",
  "open_by_handle_at",
  "clock_adjtime",
  "syncfs",
  "sendmmsg",
  "setns",
  "getcpu",
  "process_vm_readv",
  "process_vm_writev",
  "kcmp",
  "finit_module",
  "sched_setattr",
  "sched_getattr",
  "renameat2",
  "seccomp",
  "getrandom",
  "memfd_create",
  "kexec_file_load",
  "bpf",
  "execveat",
  "userfaultfd",
  "membarrier",
  "mlock2",
  "copy_file_range",
  "preadv2",
  "pwritev2",
  "pkey_mprotect",
  "pkey_alloc",
  "pkey_free",
};

static t_syscall_proto     g_syscalls_proto[] = {
	{3, "read"},
	{3, "write"},
	{3, "open"},
	{3, "open"},
	{1, "close"},
	{2, "stat"},
	{2, "fstat"},
	{2, "lstat"},
	{3, "poll"},
	{3, "lseek"},
	{3, "lseek"},
	{3, "ioctl"},
	{3, "ioctl"},
	{4, "pread64"},
	{4, "pwrite64"},
	{3, "readv"},
	{3, "readv"},
	{3, "writev"},
	{3, "writev"},
	{2, "access"},
	{1, "pipe"},
	{5, "select"},
	{5, "select"},
	{1, "dup"},
	{2, "dup2"},
	{4, "sendfile"},
	{4, "sendfile"},
	{3, "execve"},
	{3, "execve"},
	{3, "fcntl"},
	{3, "fcntl"},
	{2, "flock"},
	{1, "fsync"},
	{1, "fdatasync"},
	{2, "truncate"},
	{2, "truncate"},
	{2, "ftruncate"},
	{2, "ftruncate"},
	{3, "getdents"},
	{3, "getdents"},
	{2, "getcwd"},
	{1, "chdir"},
	{1, "fchdir"},
	{2, "rename"},
	{2, "mkdir"},
	{1, "rmdir"},
	{2, "creat"},
	{2, "link"},
	{1, "unlink"},
	{2, "symlink"},
	{3, "readlink"},
	{2, "chmod"},
	{2, "fchmod"},
	{3, "chown"},
	{3, "fchown"},
	{3, "lchown"},
	{2, "utime"},
	{2, "utime"},
	{3, "mknod"},
	{1, "uselib"},
	{2, "ustat"},
	{2, "ustat"},
	{2, "statfs"},
	{2, "statfs"},
	{2, "fstatfs"},
	{2, "fstatfs"},
	{3, "sysfs"},
	{2, "pivot_root"},
	{1, "chroot"},
	{5, "mount"},
	{5, "mount"},
	{4, "quotactl"},
	{5, "setxattr"},
	{5, "lsetxattr"},
	{5, "fsetxattr"},
	{4, "getxattr"},
	{4, "lgetxattr"},
	{4, "fgetxattr"},
	{3, "listxattr"},
	{3, "llistxattr"},
	{3, "flistxattr"},
	{2, "removexattr"},
	{2, "lremovexattr"},
	{2, "fremovexattr"},
	{2, "io_setup"},
	{2, "io_setup"},
	{1, "io_destroy"},
	{5, "io_getevents"},
	{5, "io_getevents"},
	{3, "io_submit"},
	{3, "io_submit"},
	{3, "io_cancel"},
	{3, "lookup_dcookie"},
	{4, "lookup_dcookie"},
	{1, "epoll_create"},
	{3, "getdents64"},
	{3, "getdents64"},
	{4, "epoll_wait"},
	{4, "epoll_ctl"},
	{2, "utimes"},
	{2, "utimes"},
	{3, "inotify_add_watch"},
	{2, "inotify_rm_watch"},
	{4, "openat"},
	{4, "openat"},
	{3, "mkdirat"},
	{4, "mknodat"},
	{5, "fchownat"},
	{3, "futimesat"},
	{3, "futimesat"},
	{4, "newfstatat"},
	{4, "newfstatat"},
	{3, "unlinkat"},
	{4, "renameat"},
	{5, "linkat"},
	{3, "symlinkat"},
	{4, "readlinkat"},
	{3, "fchmodat"},
	{3, "faccessat"},
	{6, "pselect6"},
	{6, "pselect6"},
	{5, "ppoll"},
	{5, "ppoll"},
	{6, "splice"},
	{4, "tee"},
	{4, "sync_file_range"},
	{4, "vmsplice"},
	{4, "vmsplice"},
	{4, "utimensat"},
	{4, "utimensat"},
	{6, "epoll_pwait"},
	{6, "epoll_pwait"},
	{3, "signalfd"},
	{3, "signalfd"},
	{2, "timerfd_create"},
	{1, "eventfd"},
	{4, "fallocate"},
	{4, "timerfd_settime"},
	{4, "timerfd_settime"},
	{2, "timerfd_gettime"},
	{2, "timerfd_gettime"},
	{4, "signalfd4"},
	{4, "signalfd4"},
	{2, "eventfd2"},
	{1, "epoll_create1"},
	{3, "dup3"},
	{2, "pipe2"},
	{1, "inotify_init1"},
	{5, "preadv"},
	{5, "preadv"},
	{5, "pwritev"},
	{5, "pwritev"},
	{2, "fanotify_init"},
	{5, "fanotify_mark"},
	{6, "fanotify_mark"},
	{5, "name_to_handle_at"},
	{3, "open_by_handle_at"},
	{3, "open_by_handle_at"},
	{1, "syncfs"},
	{5, "renameat2"},
	{5, "execveat"},
	{5, "execveat"},
	{1, "userfaultfd"},
	{6, "copy_file_range"},
	{6, "preadv2"},
	{6, "preadv2"},
	{6, "pwritev2"},
	{6, "pwritev2"},
};

char	*get_syscall_name(int num)
{
  if (num < 0 || (unsigned long)num >= sizeof(g_syscalls) / sizeof(char*))
    return (NULL);
  return (g_syscalls[num]);
}

int	get_syscall_number_params(int num)
{
  int	i;
  
  if (num < 0 || (unsigned long)num >= sizeof(g_syscalls) / sizeof(char*))
    return (-1);
  i = 0;
  while (g_syscalls_proto[i].name
	 && strcmp(g_syscalls_proto[i].name, g_syscalls[num]))
    i++;
  if (!g_syscalls_proto[i].name)
    return (-1);
  return (g_syscalls_proto[i].argc);
}
